### ISSUE TITLE
Change how Task IDs are assigned in the database

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#282] opened 2017-11-28 18:35 UTC
<img width="1054" alt="screen shot 2017-11-28 at 13 35 02" src="https://user-images.githubusercontent.com/4959135/33337446-f7e9131c-d440-11e7-8ba2-43f8f2c5bc0c.png">

**Comment by mileswwatkins** [comment] 2017-11-30 21:53
@jameslaneconkling pointed out that if we re-use Task IDs, then there could be unexpected UX if a user is manipulating tasks at the point when the worker re-creates tasks (assuming this fix would re-use task IDs). Worth considering this when making this fix.

**Comment by mileswwatkins** [comment] 2017-12-21 19:51
@geohacker, @dereklieu is probably the best point of contact as you're working on this issue. This is a minor issue, to boot.

**Comment by geohacker** [comment] 2018-01-04 14:17
If we turn off auto-increment and make it an integer wouldn't we still run into the UX problem if the order of the task generation or writing is not guaranteed? Is there a way to generate a consistent uuid per way, per task type, per province or something so this wouldn't create random hiccups? 

@dereklieu @mileswwatkins @jameslaneconkling - thoughts?

**Comment by dereklieu** [comment] 2018-01-04 20:03
These are all good points. Also, excuse my current lack of knowledge since I haven't dug into this code recently.

To step back for a bit, I think it would be simpler to use the Way ID as a means for the tasking client to inform the API that a task is completed, rather than the Task ID. 

In a common idealized scenario, if three ways overlap, the behavior right now is for the error checker to create three separate tasks - one tied to each way. The first time an operator "fixes" this task by deleting two of the three ways, all three tasks should be marked as "pending," since they are the same task.

In reality this scenario is never so simple. Usually it's more along the lines of, Ways A and B overlap completely, and Way C overlaps part of the time but also overlaps with Way D, which isn't at all connected to Ways A and B. All four ways, A, B, C, and D, have their own tasks, which are mostly the same task (but not exactly the same).

At this point it gets hairy to decide which of these overlapping tasks to mark as Pending when a user chooses to delete way B. Having a unique Task ID here would not help you solve this.

Right now the error checker is fast but dumb, and the API logic for marking tasks as pending is overly simplistic. Two approaches could be:

1. Make the error checker slower, but less prone to creating many copies of the same task. IE, maybe we could dedupe all the tasks the contain the same way IDs, since they are probably the same task.
2. Be smarter on the API side about how to mark tasks as pending. This could involve changing what we ask of the user, in order to get better signal to the API.

To return to the initial topic, I don't think we should put too much effort into the issue of Task IDs changing between error checking runs. Even if the Task ID changed, if we can assume that the Way geometries being "fixed" haven't changed, than we can still mark the appropriate tasks as pending (or if no tasks remain with those ways, than do nothing).

I think I attempted this with my initial approach but probably didn't pull it off very well.

**Comment by geohacker** [comment] 2018-01-25 15:48
I agree with @dereklieu on not putting much effort right now. There are some more ideas we can kick around on making tasking a bit more tightly integrated to the whole process. For instance, if we make the task module run against every change for ways in the database, we can reliably remove the cron based trigger and inconsistencies that may arise. 

cc @kamicut because we talked a bit about this yesterday.

**Comment by geohacker** [comment] 2018-02-09 11:38
We'll roll this into P4 to make tasks a bit better. This isn't really a bug or regression.

**Closed** 2018-06-27 08:51 UTC
