### ISSUE TITLE
[Asset][The system got crashed after inputing VProMMId]

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#575] opened 2019-02-22 07:38 UTC
1. Input VProMM ID = 075CH00002 and then click Save button at the Add new Asset pop-up. 
- Actual result: Data of Total and Field Data is displayed 0
+ The correct page is not shown after click hyperlink: Province, VProMM ID, Add Asset.
![image](https://user-images.githubusercontent.com/38553180/53227006-8b8d9800-36af-11e9-8000-98202077d1ec.png)

**Comment by batpad** [comment] 2019-02-22 09:36
Thanks for this report @tailm1 .

@geohacker - this seems to be caused because the list of provinces has not been updated on the frontend, causing issues when the user adds a VPRoMM to a province that is not in the frontend list.

Have filed an issue to update the province list: https://github.com/orma/openroads-vn-analytics/issues/583

**Comment by geohacker** [comment] 2019-02-22 09:53
Duplicate of #583

**Comment by batpad** [comment] 2019-02-22 11:37
@geohacker can we leave this open until we confirm that #583 does indeed fix this?

**Closed** 2019-03-05 08:00 UTC
Labels: bug, v3-feedback
