### ISSUE TITLE
Check road data in Thanh Hoa

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#381] opened 2018-01-26 08:04 UTC
Data in Bim Son town belongs to Ba Thuoc District. Data in Thanh Hoa City belongs to Provincial roads.

![8](https://user-images.githubusercontent.com/31137016/35430286-84af1146-026f-11e8-98e4-1eae4eabf437.jpg)

**Comment by geohacker** [comment] 2018-02-13 09:38
![image](https://user-images.githubusercontent.com/371666/36141618-55ee49de-10cb-11e8-812a-5b1081614e7e.png)

_Thanh Hoa_

![image](https://user-images.githubusercontent.com/371666/36142849-3f82d4b8-10cf-11e8-9658-2cdc47db68b3.png)
_Ba Thuoc (green) and Bim Son (blue)_

@PCDuc I verified the geometries for both the districts. The ones with vprommids seems correct to me. But I think I'm not sure what you mean here by the mix up. Can you explain with examples? Thank you!

**Comment by PCDuc** [comment] 2018-02-13 11:10
@geohacker 
What I mean is, in this project, we won't have any VPRoMMS IDs for Bim Son Town and Thanh Hoa City.
- The VPRoMMS IDs in Bim Son Town (show in ORMA/Asset) are duplicates of VPRoMMS IDs in Ba Thuoc District. So, you may simply delete all VPRoMMS IDs in Bim Son Town.
- The VPRoMMS IDs in Thanh Hoa City (show in ORMA/Asset) is actually the provincial roads (not the roads inside Thanh Hoa City, but are the backbone of whole province). In this case, I suggest to create a new sub-folder, name 'Provincial roads' and move all VPRoMMS IDs in Thanh Hoa City folder to the new one.
I hope it may be clearer. Let's talk if needed. Thanks!

**Comment by geohacker** [comment] 2018-02-13 11:29
So trying to dig a bit more here. There seems to be two different processes:

1. Ingesting admin boundaries into the database via https://github.com/orma/openroads-vn-boundaries/tree/develop - this all looks okay to me. And has nothing to do with the current issue.
2. Crosswalk to match road vpromm to commune(?)[ using a crosswalk o](https://github.com/orma/openroads-vn-analytics/issues/173#issuecomment-361302853)n the front-end using the [list here](https://github.com/orma/openroads-vn-analytics/blob/master/app/assets/scripts/constants.js). But I can't seem to find any references to that code in the current state https://github.com/orma/openroads-vn-analytics/search?utf8=%E2%9C%93&q=constants.js&type=

**Comment by geohacker** [comment] 2018-02-14 09:51
![image](https://user-images.githubusercontent.com/371666/36197387-98c98984-1199-11e8-96d3-af539fe2008e.png)

This is from @PCDuc to clarify the code. 

> The VPRoMMS IDs in Bim Son Town (show in ORMA/Asset) are duplicates of VPRoMMS IDs in Ba Thuoc District. So, you may simply delete all VPRoMMS IDs in Bim Son Town.

The problem is that Bim Son Town and Ba Thuoc have the same district code `BT`. See here https://github.com/orma/openroads-vn-analytics/blob/develop/app/assets/scripts/constants.js#L422-L429. And they both happen to be the same province Thahn Hoa. 

@PCDuc - could this code be a mistake? Is there a canonical list of district codes we can verify against? 

Regarding your second observation:

> The VPRoMMS IDs in Thanh Hoa City (show in ORMA/Asset) is actually the provincial roads (not the roads inside Thanh Hoa City, but are the backbone of whole province). In this case, I suggest to create a new sub-folder, name 'Provincial roads' and move all VPRoMMS IDs in Thanh Hoa City folder to the new one.

I'm not sure what the best approach here is. My assumption was that we're working in Thanh Hoa and these are all roads in that geography. @olafveerman do you have any idea why these are a different class of roads now? cc @sarahantos

**Comment by geohacker** [comment] 2018-02-16 04:20
@PCDuc any thoughts? Do you have a list of district codes I can verify against? Thank you!

**Comment by PCDuc** [comment] 2018-02-16 04:48
@geohacker I don't have that list because I think it was generated from your side to match the data. But you may want to change Bim Son Town code to BS and Sam Son Town to SS instead of SST. Thank you!

**Comment by geohacker** [comment] 2018-02-16 11:41
Thank you @PCDuc! This is fixed. I'm not sure what's the best approach for the non province roads. We'll wait to hear from rest of the team. 

I'm closing this for now.

**Closed by geohacker** 2018-02-16 11:41 UTC
Labels: bug
