### ISSUE TITLE
Create full-network dump, routable if possible

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#79] opened 2017-09-11 18:15 UTC
Output format should be in OSM XML, for easiest integration with Rural Accessibility Map.

**Comment by mileswwatkins** [comment] 2017-10-04 02:10
Full-network OSM XML dump pushed to phase 2

**Comment by mileswwatkins** [comment] 2017-12-20 22:14
There should be both a routable and a non-routable dump, per discussion with @sarahantos and @PCDuc this morning. The non-routable dump will be useful for non-core users such as Duc, running ad-hoc analytics. It shouldn't be surfaced, generally speaking, to most users.

**Comment by geohacker** [comment] 2018-02-12 08:28
Duplicate of https://github.com/orma/openroads-vn-analytics/issues/351

**Closed by geohacker** 2018-02-12 08:28 UTC
Labels: enhancement, workflow
