### ISSUE TITLE
Unable to Sort and Filtering in Asset Page 

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#582] opened 2019-02-22 08:05 UTC
Go To Asset Page
Expectation : Users able to sort and filter admin/asset by click in column header

**Comment by geohacker** [comment] 2019-02-22 09:29
This is duplicate of https://github.com/orma/openroads-vn-analytics/issues/520 - and is an enhancement we can consider for the next phase of work. Thank you for opening the issue!

**Closed by geohacker** 2019-02-22 09:29 UTC

**Comment by tailm1** [comment] 2019-02-23 11:55
Please note that we expect filtering function for each column also.
