### ISSUE TITLE
Task - filter tasks by district

### ISSUE THREAD

**Issue by sarahantos** [orma/openroads-vn-analytics#402] opened 2018-02-02 21:51 UTC
Help to focus on  smaller working area by allowing users to choose district to work in.

Showing the total number of tasks in a chosen area

**Comment by geohacker** [comment] 2018-02-05 14:53
The tasks interface will already let the user select the province they would like to work on. And the task count is reflective of what's in the province. 

Are you suggesting that we should have a default province selected?

**Comment by dereklieu** [comment] 2018-05-10 21:59
Can we clarify next steps here @sarahantos? I wonder if fixing #425 would help working on tasks feel more manageable.

**Comment by sarahantos** [comment] 2018-05-11 13:36
i dont know how easy this would be, so its just an idea. How about showing either on the map or in a list, all of the tasks that a person needs to fix in a certain province. this would allow people to easily understand what problem areas they have left. I would suggest you having a friend/member of dev seed, who isn't familar with the site, try to fix some lines and get some feedback from them on UX

**Comment by geohacker** [comment] 2018-08-03 16:27
We already have province filters, what's missing is district filters. Here are the steps for doing this:

**Comment by olafveerman** [comment] 2018-10-04 11:55
All the backend work has been done, the only remaining task is to implement this in the interface.

**Comment by geohacker** [comment] 2018-10-19 11:29
Done!

**Comment by olafveerman** [comment] 2018-10-29 20:32
Feedback 

Anh: It works well now (in EN)

Do: 
1/ I encountered some issues when using filter and search function.
ref video: https://drive.google.com/file/d/1ot5Dgo5Q69UBjml0OTMIwt62IgQrDxHC/view?usp=sharing
Please check the problem.

2/ Some comments of mine, relating to make filter more useful for user:
It's a common case of the user who want to find a certain class/level of road such as only commune roads. Additionally, another user's case is that sometimes the staff would like to see whether roads have data or not. Therefore, there should be filter features with road classes/levels and status based on availability of data

cc @geohacker

**Comment by geohacker** [comment] 2018-10-30 05:40
Thank you for reopening @olafveerman. 

> 1/ I encountered some issues when using filter and search function.
ref video: https://drive.google.com/file/d/1ot5Dgo5Q69UBjml0OTMIwt62IgQrDxHC/view?usp=sharing
Please check the problem.

This is a duplicate of #492. The incorrect listing of assets in other provinces was caused by a mismatch of provincial and district codes. This is now fixed. http://openroads-vn.com/#/en/assets/338

> It's a common case of the user who want to find a certain class/level of road such as only commune roads. 

This is a feature request. Previously we only wanted to be able to search for assets and admin boundaries in the Assets page. But I will open a new ticket to capture this request.

**Closed** 2018-10-30 10:37 UTC
Labels: medium
